const {
  VITE_TRIP_DESTINATION_API_BASE_URL,
  VITE_TRIP_DESTINATION_API_ENDPOINT,
  VITE_TRIP_DESTINATION_IMAGE_API_BASE_URL,
  VITE_TRIP_DESTINATION_IMAGE_ENDPOINT,
} = import.meta.env

export const appConfig = {
  TRIP_DESTINATION_API_URL:
    `${VITE_TRIP_DESTINATION_API_BASE_URL}${VITE_TRIP_DESTINATION_API_ENDPOINT}` ||
    'https://swapi.py4e.com/api/planets',
  TRIP_DESTINATION_IMAGE_API_URL:
    `${VITE_TRIP_DESTINATION_IMAGE_API_BASE_URL}${VITE_TRIP_DESTINATION_IMAGE_ENDPOINT}` ||
    'https://images.ferryhopper.com/locations',
} as const
