const {
  VITE_TRIP_DESTINATION_API_BASE_URL,
  VITE_TRIP_DESTINATION_API_ENDPOINT,
  VITE_TRIP_DESTINATION_IMAGE_API_BASE_URL,
  VITE_TRIP_DESTINATION_IMAGE_ENDPOINT,

  VITE_STORE_KEY_PLANET_DESTINATIONS,
  VITE_STORE_KEY_TRIP_PLAN,
  VITE_STORE_KEY_PAGE_NUMBER,
  VITE_TRIP_PLAN_DESTINATIONS_MAX_NUMBER,
} = import.meta.env

export const appConfig = {
  TRIP_DESTINATION_API_URL:
    `${VITE_TRIP_DESTINATION_API_BASE_URL}${VITE_TRIP_DESTINATION_API_ENDPOINT}` ||
    'https://swapi.py4e.com/api/planets',
  TRIP_DESTINATION_IMAGE_API_URL:
    `${VITE_TRIP_DESTINATION_IMAGE_API_BASE_URL}${VITE_TRIP_DESTINATION_IMAGE_ENDPOINT}` ||
    'https://images.ferryhopper.com/locations',
  TRIP_PLAN_DESTINATIONS_MAX_NUMBER: VITE_TRIP_PLAN_DESTINATIONS_MAX_NUMBER || 5,

  STORE_KEY_PLANET_DESTINATIONS: VITE_STORE_KEY_PLANET_DESTINATIONS || 'planet_destinations',
  STORE_KEY_TRIP_PLAN: VITE_STORE_KEY_TRIP_PLAN || 'trip_plan_items',
  STORE_KEY_PAGE_NUMBER: VITE_STORE_KEY_PAGE_NUMBER || 'page_number',
} as const
